### ISSUE TITLE
Error on 1.21.3

### ISSUE THREAD

**Issue by MinerFixed** [mries92/EnderBag#11]
Could you please look into an error that occurs on Minecraft 1.21.3?

I am using: This server is running Paper version 1.21.3-61-master@cd9e697 (2024-11-25T16:11:04Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

It doesn't affect functionality of the plugin, as far as I know, it just spams in the console. Thank you

`[16:00:31 ERROR]: Could not pass event PlayerInteractEvent to EnderBag v1.1.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because the return value of "org.bukkit.inventory.ItemStack.getItemMeta()" is null
        at EnderBag.jar/org.mries.enderbag.ItemManager.isEnderChest(ItemManager.java:52) ~[EnderBag.jar:?]
        at EnderBag.jar/org.mries.enderbag.EventListener.onRightClick(EventListener.java:31) ~[EnderBag.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:41) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1957) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-61-cd9e697]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by MinerFixed** [comment]
I've also got plugin OpenInv installed, that might cause the error, not sure

**Comment by mries92** [comment]
Thanks for the bug report! I think this is simply because you are on such an old version `1.1.0`. I was unable to reproduce this issue using the latest versions. Please update and let me know if this still occurs. I have just published `1.6.0`.

**Comment by MinerFixed** [comment]
Ahh, thank you!! I didn't notice there is new versions, appreciate it, thanks

**Comment by mries92** [comment]
Glad that fixed it for you :)
